name: CI Pipeline

on:
  workflow_call:

jobs:
  test-build:
    runs-on: ubuntu-latest
    env:
      JENKINS_NODE_COOKIE: 'dontKillMe'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clean temp workspace
        run: |
          find /tmp -user runner -print0 | xargs -0 rm -rf
          echo "running build in temp workspace"
          mv config.example.ts config.ts

      - name: Install dependencies
        run: |
          npm run clean
          npm cache clean --force
          rm -rf node_modules
          npm install

      - name: Build project
        run: npm run build
        continue-on-error: true

      - name: Send Discord notification (Test Build)
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
            -d '{"content":"Test build failed on branch [${{ github.ref_name }}](https://github.com/ud-cis-discord/SageV2/commit/${{ github.sha }})"}' \
            ${{ secrets.DISCORD_WEBHOOK }}

  lint:
    runs-on: ubuntu-latest
    needs: test-build
    steps:
      - name: Lint and Test
        run: |
          echo "Running tests in temp workspace"
          npm run test
        continue-on-error: true

      - name: Send Discord notification (Lint)
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
            -d '{"content":"Lint failed on branch [${{ github.ref_name }}](https://github.com/ud-cis-discord/SageV2/commit/${{ github.sha }})"}' \
            ${{ secrets.DISCORD_WEBHOOK }}

  deploy:
    runs-on: ubuntu-latest
    needs: lint
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to production
        run: |
          echo "Deploying to production"
          cd $SAGE_DIR
          git pull
          npm run clean
          npm install
          npm run build
          sudo /bin/systemctl restart sage
        continue-on-error: true

      - name: Send Discord notification (Deploy)
        run: |
          curl -H "Content-Type: application/json" \
            -d '{"content":"Deployment on branch [${{ github.ref_name }}] complete"}' \
            ${{ secrets.DISCORD_WEBHOOK }}

  update-docs:
    runs-on: ubuntu-latest
    needs: deploy
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Update documentation
        run: |
          echo "Updating documentation"
          cd $SAGE_DIR
          npm run autodoc
        continue-on-error: true

      - name: Send Discord notification (Update Docs)
        run: |
          curl -H "Content-Type: application/json" \
            -d '{"content":"Documentation updated on branch [${{ github.ref_name }}]"}' \
            ${{ secrets.DISCORD_WEBHOOK }}