name: Deploy

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to production
        if: github.ref == 'refs/heads/main'
        run: |
          cd ${{ env.SAGE_DIR }}
          git pull
          npm run clean
          npm i
          npm run build
          sudo /bin/systemctl restart sage