name: Discord Message

on:
  push:
    branches:
      - main

jobs:
  send_message:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord Message
        uses: appleboy/discord-action@v1
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          message: "Hello from GitHub Actions!"