name: Main Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
  MAIN_BRANCH: 'main'
  SAGE_DIR: '/usr/local/sage/SageV2'

jobs:

  lint:
    uses: ./.github/workflows/lint.yml
