name: Main Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
  MAIN_BRANCH: 'main'
  SAGE_DIR: '/usr/local/sage/SageV2'

jobs:
  test-build:
    uses: ./.github/workflows/test-build.yml

  lint:
    needs: test-build
    uses: ./.github/workflows/lint.yml

  update-docs:
    needs: deploy
    uses: ./.github/workflows/update-docs.yml
    if: github.ref == 'refs/heads/main'