name: CI Pipeline

on:
  push:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Get Repo Values
        id: get-repo-values
        run: |
          url=https://$(echo "${{ github.repository }}" | sed "s/\//.github.io\//")
          echo "url=$url" >> $GITHUB_ENV

      - name: Install Dependencies
        run: npm ci

      - name: Test Build
        run: |
          echo "running build in temp workspace"
          npm run clean
          npm cache clean --force
          find . -maxdepth 1 -type d -name 'node_modules' -exec rm -rf {} +
          npm install
          npm run build
      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test -- --coverage |& tee ./public/test_report.txt

      - name: Create GitHub HTML
        run: echo "<html><head><meta http-equiv='refresh' content='0; URL=${{ github.server_url }}/${{ github.repository }}' /></head><body>Redirecting to repository</body></html>" > ./public/github.html

      - name: Build (if present)
        run: npm run build --if-present

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          echo "rebuilding and deploying in prod directory..."
          cd ${{ env.SAGE_DIR }}
          git pull
          npm run clean
          npm install
          npm run build
          sudo /bin/systemctl restart sage

      - name: Update Docs
        if: github.ref == 'refs/heads/main'
        run: |
          echo "automatically updating the documentation website"
          cd ${{ env.SAGE_DIR }}
          npm run autodoc
