# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: node

on:
  push:
    branches: [ "main", "Ava-branch" ]
  pull_request:
    branches: [ "main", "Ava-branch" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '>=18'
        cache: 'npm'
    - run: npm cache clean --force
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test