name: Sage Workflow

on:
  push:
    branches:
      - main

env:
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
  MAIN_BRANCH: main
  SAGE_DIR: /usr/local/sage/SageV2
  JENKINS_NODE_COOKIE: dontKillMe

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: |
          npm ci

      - name: Test Build
        run: |
          echo "running build in temp workspace"
          npm run build

      - name: Lint
        run: |
          npm run lint
          npm run test

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          echo "rebuilding and deploying in prod directory..."
          npm run dev

      - name: Update Docs
        if: github.ref == 'refs/heads/main'
        run: |
          echo "automatically updating the documentation website"
          cd ${{ env.SAGE_DIR }}
          npm run autodoc