name: CI Pipeline

on:
  push:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install Dependencies
        run: |
          npm install

      - name: Test Build
        run: |
          echo "running build in temp workspace"
          npm run clean
          npm cache clean --force
          rm -rf node_modules
          npm install
          npm run build

      - name: Lint
        run: |
          echo "testing in temp workspace..."
          npm run test

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          echo "rebuilding and deploying in prod directory..."
          cd ${{ env.SAGE_DIR }}
          git pull
          npm run clean
          npm install
          npm run build
          sudo /bin/systemctl restart sage

      - name: Update Docs
        if: github.ref == 'refs/heads/main'
        run: |
          echo "automatically updating the documentation website"
          cd ${{ env.SAGE_DIR }}
          npm run autodoc
