name: Test Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Clean temp files
        run: |
          find /tmp -user $USER -print0 | xargs -0 rm -rf
      - name: Prepare config
        run: mv config.example.ts config.ts
      - name: Clean and install dependencies
        run: |
          npm run clean
          npm cache clean --force
          rm -rf node_modules
          npm i
      - name: Build
        run: npm run build